[project]
name = "basicnnwithpytorch"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "import-ipynb>=0.2",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.1",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
]


